//-------------------------------------------------------
// Autogenerated from 'vmut_vendor_mini.vmf'
//-------------------------------------------------------
::VMutVendorMiniEnt <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.prop_machine,
			EntityGroup.SpawnTables.prop_item,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.prop_item,
			EntityGroup.SpawnTables.deploy_target,
			EntityGroup.SpawnTables.prop_machine,
			EntityGroup.SpawnTables.price_display_target,
			EntityGroup.SpawnTables.root,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			prop_machine = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 270, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "255 255 255"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "1"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props/cs_militia/microwave01.mdl"
					parentname = "root"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "prop_machine"
					updatechildren = "0"
					origin = Vector( 0, 0, 0 )
				}
			}
			prop_item = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "140"
					glowrangemin = "0"
					glowstate = "3"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/w_models/weapons/w_eq_medkit.mdl"
					parentname = "root"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "prop_item"
					updatechildren = "0"
					origin = Vector( 0, 0, 30 )
				}
			}
			deploy_target = 
			{
				SpawnInfo =
				{
					classname = "info_target"
					angles = Vector( 0, 0, 0 )
					parentname = "root"
					spawnflags = "0"
					targetname = "deploy_target"
					origin = Vector( 0, -24, 8 )
				}
			}
			price_display_target = 
			{
				SpawnInfo =
				{
					classname = "info_target"
					angles = Vector( 0, 0, 0 )
					parentname = "root"
					spawnflags = "0"
					targetname = "price_display_target"
					origin = Vector( -16, -14, 16 )
				}
			}
			root = 
			{
				SpawnInfo =
				{
					classname = "info_target"
					angles = Vector( 0, 0, 0 )
					spawnflags = "0"
					targetname = "root"
					origin = Vector( 0, 0, 0 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // VmutVendorMini

RegisterEntityGroup( "VMutVendorMiniEnt", ::VMutVendorMiniEnt )
