//-------------------------------------------------------
// Autogenerated from 'vmut_supply_balloon.vmf'
//-------------------------------------------------------
VmutSupplyBalloon <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.balloon,
			EntityGroup.SpawnTables.supply_crate,
			EntityGroup.SpawnTables.explode,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.spring2,
			EntityGroup.SpawnTables.thruster_side,
			EntityGroup.SpawnTables.rope4_top,
			EntityGroup.SpawnTables.rope2_top,
			EntityGroup.SpawnTables.rope3_top,
			EntityGroup.SpawnTables.unpack_relay,
			EntityGroup.SpawnTables.spring3,
			EntityGroup.SpawnTables.rope1_bottom,
			EntityGroup.SpawnTables.balloon,
			EntityGroup.SpawnTables.explode,
			EntityGroup.SpawnTables.thruster_up,
			EntityGroup.SpawnTables.supply_crate,
			EntityGroup.SpawnTables.spring1,
			EntityGroup.SpawnTables.rope_kill_relay,
			EntityGroup.SpawnTables.rope3_bottom,
			EntityGroup.SpawnTables.spring4,
			EntityGroup.SpawnTables.supply_crate_usetarget,
			EntityGroup.SpawnTables.explode_relay,
			EntityGroup.SpawnTables.rope4_bottom,
			EntityGroup.SpawnTables.rope2_bottom,
			EntityGroup.SpawnTables.rope1_top,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			balloon = 
			{
				SpawnInfo =
				{
					classname = "prop_physics_multiplayer"
					angles = Vector( 0, 0, 0 )
					body = "0"
					BreakableType = "0"
					damagetoenablemotion = "0"
					Damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					inertiaScale = "1.0"
					massScale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_unique/airport/atlas_break_ball.mdl"
					nodamageforces = "0"
					overridescript = "mass,10"
					PerformanceMode = "0"
					physdamagescale = "0.1"
					physicsmode = "0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "514"
					targetname = "balloon"
					origin = Vector( 0, 0, 0 )
					connections =
					{
						OnTakeDamage =
						{
							cmd1 = "explode_relayTrigger0-1"
						}
					}
				}
			}
			explode_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "1"
					StartDisabled = "0"
					targetname = "explode_relay"
					origin = Vector( -128, 0, 0 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "explodeExplode0-1"
							cmd2 = "rope_kill_relayTrigger0-1"
							cmd3 = "thruster_sideKill0-1"
							cmd4 = "thruster_upKill0-1"
							cmd5 = "balloonKill0-1"
						}
					}
				}
			}
			supply_crate = 
			{
				SpawnInfo =
				{
					classname = "prop_physics_multiplayer"
					angles = Vector( 0, 0, 0 )
					body = "0"
					BreakableType = "0"
					damagetoenablemotion = "0"
					Damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					inertiaScale = "1.0"
					massScale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props/de_nuke/crate_small.mdl"
					nodamageforces = "0"
					overridescript = "mass,50"
					PerformanceMode = "0"
					physdamagescale = "0.1"
					physicsmode = "0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "256"
					targetname = "supply_crate"
					origin = Vector( 0, 0, 0 )
				}
			}
			supply_crate_usetarget = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "supply_crate"
					origin = Vector( 0, 0, 32 )
					targetname = "supply_crate_usetarget"
					vscripts = "vmut/vmut_supply_crate_usetarget.nut"
					connections =
					{
						OnUseFinished =
						{
							cmd1 = "unpack_relayTrigger0-1"
						}
					}
				}
			}
			rope1_bottom = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 0, 0 )
					Barbed = "0"
					Breakable = "0"
					Collide = "0"
					Dangling = "0"
					disableX360 = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					MoveSpeed = "64"
					NextKey = "rope1_top"
					parentname = "supply_crate"
					PositionInterpolator = "2"
					RopeMaterial = "cable/cable.vmt"
					Slack = "16"
					spawnflags = "0"
					Subdiv = "2"
					targetname = "rope1_bottom"
					TextureScale = "1"
					Type = "0"
					UseWind = "0"
					Width = "2"
					origin = Vector( 0, 32, 64 )
				}
			}
			rope1_top = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 0, 0 )
					Barbed = "0"
					Breakable = "0"
					Collide = "0"
					Dangling = "0"
					disableX360 = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					MoveSpeed = "64"
					parentname = "balloon"
					PositionInterpolator = "2"
					RopeMaterial = "cable/cable.vmt"
					Slack = "16"
					spawnflags = "0"
					Subdiv = "2"
					targetname = "rope1_top"
					TextureScale = "1"
					Type = "0"
					UseWind = "0"
					Width = "2"
					origin = Vector( 0, 56, 160 )
				}
			}
			rope3_top = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 0, 0 )
					Barbed = "0"
					Breakable = "0"
					Collide = "0"
					Dangling = "0"
					disableX360 = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					MoveSpeed = "64"
					parentname = "balloon"
					PositionInterpolator = "2"
					RopeMaterial = "cable/cable.vmt"
					Slack = "16"
					spawnflags = "0"
					Subdiv = "2"
					targetname = "rope3_top"
					TextureScale = "1"
					Type = "0"
					UseWind = "0"
					Width = "2"
					origin = Vector( 0, -56, 160 )
				}
			}
			rope4_top = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 0, 0 )
					Barbed = "0"
					Breakable = "0"
					Collide = "0"
					Dangling = "0"
					disableX360 = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					MoveSpeed = "64"
					parentname = "balloon"
					PositionInterpolator = "2"
					RopeMaterial = "cable/cable.vmt"
					Slack = "16"
					spawnflags = "0"
					Subdiv = "2"
					targetname = "rope4_top"
					TextureScale = "1"
					Type = "0"
					UseWind = "0"
					Width = "2"
					origin = Vector( 56, 0, 160 )
				}
			}
			rope2_top = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 0, 0 )
					Barbed = "0"
					Breakable = "0"
					Collide = "0"
					Dangling = "0"
					disableX360 = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					MoveSpeed = "64"
					parentname = "balloon"
					PositionInterpolator = "2"
					RopeMaterial = "cable/cable.vmt"
					Slack = "16"
					spawnflags = "0"
					Subdiv = "2"
					targetname = "rope2_top"
					TextureScale = "1"
					Type = "0"
					UseWind = "0"
					Width = "2"
					origin = Vector( -56, 0, 160 )
				}
			}
			rope3_bottom = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 0, 0 )
					Barbed = "0"
					Breakable = "0"
					Collide = "0"
					Dangling = "0"
					disableX360 = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					MoveSpeed = "64"
					NextKey = "rope3_top"
					parentname = "supply_crate"
					PositionInterpolator = "2"
					RopeMaterial = "cable/cable.vmt"
					Slack = "16"
					spawnflags = "0"
					Subdiv = "2"
					targetname = "rope3_bottom"
					TextureScale = "1"
					Type = "0"
					UseWind = "0"
					Width = "2"
					origin = Vector( 0, -32, 64 )
				}
			}
			rope2_bottom = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 0, 0 )
					Barbed = "0"
					Breakable = "0"
					Collide = "0"
					Dangling = "0"
					disableX360 = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					MoveSpeed = "64"
					NextKey = "rope2_top"
					parentname = "supply_crate"
					PositionInterpolator = "2"
					RopeMaterial = "cable/cable.vmt"
					Slack = "16"
					spawnflags = "0"
					Subdiv = "2"
					targetname = "rope2_bottom"
					TextureScale = "1"
					Type = "0"
					UseWind = "0"
					Width = "2"
					origin = Vector( -32, 0, 64 )
				}
			}
			rope4_bottom = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 0, 0 )
					Barbed = "0"
					Breakable = "0"
					Collide = "0"
					Dangling = "0"
					disableX360 = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					MoveSpeed = "64"
					NextKey = "rope4_top"
					parentname = "supply_crate"
					PositionInterpolator = "2"
					RopeMaterial = "cable/cable.vmt"
					Slack = "16"
					spawnflags = "0"
					Subdiv = "2"
					targetname = "rope4_bottom"
					TextureScale = "1"
					Type = "0"
					UseWind = "0"
					Width = "2"
					origin = Vector( 32, 0, 64 )
				}
			}
			explode = 
			{
				SpawnInfo =
				{
					classname = "env_explosion"
					fireballsprite = "sprites/zerogxplode.spr"
					ignoredClass = "0"
					iMagnitude = "100"
					iRadiusOverride = "0"
					parentname = "balloon"
					rendermode = "5"
					spawnflags = "1"
					targetname = "explode"
					origin = Vector( 0, 0, 160 )
				}
			}
			rope_kill_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "1"
					StartDisabled = "0"
					targetname = "rope_kill_relay"
					origin = Vector( -128, -48, 0 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "rope1_bottomKill0-1"
							cmd2 = "rope1_topKill0-1"
							cmd3 = "rope2_bottomKill0-1"
							cmd4 = "rope2_topKill0-1"
							cmd5 = "rope3_bottomKill0-1"
							cmd6 = "rope3_topKill0-1"
							cmd7 = "rope4_bottomKill0-1"
							cmd8 = "rope4_topKill0-1"
							cmd9 = "spring1Kill0-1"
							cmd10 = "spring2Kill0-1"
							cmd11 = "spring3Kill0-1"
							cmd12 = "spring4Kill0-1"
						}
					}
				}
			}
			thruster_side = 
			{
				SpawnInfo =
				{
					classname = "phys_thruster"
					angles = Vector( 0, 0, 0 )
					attach1 = "balloon"
					force = "2250"
					forcetime = "0"
					spawnflags = "57"
					targetname = "thruster_side"
					origin = Vector( 0, 0, 232 )
				}
			}
			thruster_up = 
			{
				SpawnInfo =
				{
					classname = "phys_thruster"
					angles = Vector( 0, -90, 0 )
					attach1 = "balloon"
					force = "600"
					forcetime = "0"
					spawnflags = "57"
					targetname = "thruster_up"
					origin = Vector( 0, 0, 256 )
				}
			}
			spring2 = 
			{
				SpawnInfo =
				{
					classname = "phys_spring"
					attach1 = "balloon"
					attach2 = "supply_crate"
					breaklength = "0"
					constant = "50"
					damping = "6"
					length = "0"
					relativedamping = "0.1"
					spawnflags = "0"
					springaxis = Vector( 0, 32, 64 )
					targetname = "spring2"
					origin = Vector( 0, 32, 64 )
				}
			}
			spring3 = 
			{
				SpawnInfo =
				{
					classname = "phys_spring"
					attach1 = "balloon"
					attach2 = "supply_crate"
					breaklength = "0"
					constant = "50"
					damping = "6"
					length = "0"
					relativedamping = "0.1"
					spawnflags = "0"
					springaxis = Vector( -32, 0, 64 )
					targetname = "spring3"
					origin = Vector( -32, 0, 64 )
				}
			}
			spring4 = 
			{
				SpawnInfo =
				{
					classname = "phys_spring"
					attach1 = "balloon"
					attach2 = "supply_crate"
					breaklength = "0"
					constant = "50"
					damping = "6"
					length = "0"
					relativedamping = "0.1"
					spawnflags = "0"
					springaxis = Vector( 0, -32, 64 )
					targetname = "spring4"
					origin = Vector( 0, -32, 64 )
				}
			}
			spring1 = 
			{
				SpawnInfo =
				{
					classname = "phys_spring"
					attach1 = "balloon"
					attach2 = "supply_crate"
					breaklength = "0"
					constant = "50"
					damping = "6"
					length = "0"
					relativedamping = "0.1"
					spawnflags = "0"
					springaxis = Vector( 32, 0, 64 )
					targetname = "spring1"
					origin = Vector( 32, 0, 64 )
				}
			}
			unpack_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "1"
					StartDisabled = "0"
					targetname = "unpack_relay"
					origin = Vector( -128, 48, 0 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "supply_crate_usetargetKill0-1"
							cmd2 = "supply_crateKill0-1"
						}
					}
				}
			}
		} // SpawnTables
	} // EntityGroup
} // VmutSupplyBalloon

RegisterEntityGroup( "VmutSupplyBalloon", VmutSupplyBalloon )
