//-------------------------------------------------------
// Autogenerated from 'vmut_currency_pickup.vmf'
//-------------------------------------------------------
VMutCurrencyPickup <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.prop,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.prop,
			EntityGroup.SpawnTables.pickup,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			prop = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_collectables/money_wad.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "prop"
					updatechildren = "0"
					origin = Vector( 0, 0, 0 )
				}
			}
			pickup = 
			{
				SpawnInfo =
				{
					classname = "script_func_button"
					disablereceiveshadows = "0"
					disableX360 = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glow = "prop"
					health = "0"
					lip = "0"
					locked_sentence = "0"
					locked_sound = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					movedir = "0 0 0"
					origin = Vector( 0, 0, 2 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					sounds = "0"
					spawnflags = "1024"
					speed = "5"
					targetname = "pickup"
					unlocked_sentence = "0"
					unlocked_sound = "0"
					wait = "3"
					extent = Vector( 8, 8, 6 )
					connections =
					{
						OnPressed =
						{
							cmd1 = "propKill0-1"
							cmd2 = "buttonKill0-1"
							cmd3 = "scriptRunScriptCodePickup()0-1"
						}
					}
				}
			}
		} // SpawnTables
	} // EntityGroup
} // VMutCurrencyPickup

RegisterEntityGroup( "VMutCurrencyPickup", VMutCurrencyPickup )
