//-------------------------------------------------------
// Autogenerated from 'vmut_vendor.vmf'
//-------------------------------------------------------
::VMutVendorEnt <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.prop_machine,
			EntityGroup.SpawnTables.prop_item,
			EntityGroup.SpawnTables.explode,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.root,
			EntityGroup.SpawnTables.price_display_target,
			EntityGroup.SpawnTables.prop_machine,
			EntityGroup.SpawnTables.explode,
			EntityGroup.SpawnTables.prop_item,
			EntityGroup.SpawnTables.deploy_target,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			prop_machine = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "255 255 255"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "1"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_office/vending_machine01.mdl"
					parentname = "root"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "prop_machine"
					updatechildren = "0"
					origin = Vector( 0, 0, 0 )
				}
			}
			prop_item = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "140"
					glowrangemin = "0"
					glowstate = "3"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/w_models/weapons/w_eq_medkit.mdl"
					parentname = "root"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "prop_item"
					updatechildren = "0"
					origin = Vector( 0, 0, 96 )
				}
			}
			deploy_target = 
			{
				SpawnInfo =
				{
					classname = "info_target"
					angles = Vector( 0, 0, 0 )
					parentname = "root"
					spawnflags = "0"
					targetname = "deploy_target"
					origin = Vector( 0, -24, 16 )
				}
			}
			price_display_target = 
			{
				SpawnInfo =
				{
					classname = "info_target"
					angles = Vector( 0, 0, 0 )
					parentname = "root"
					spawnflags = "0"
					targetname = "price_display_target"
					origin = Vector( -22, -8, 64 )
				}
			}
			root = 
			{
				SpawnInfo =
				{
					classname = "info_target"
					angles = Vector( 0, 0, 0 )
					spawnflags = "0"
					targetname = "root"
					origin = Vector( 0, 0, 0 )
				}
			}
			explode = 
			{
				SpawnInfo =
				{
					classname = "env_explosion"
					fireballsprite = "sprites/zerogxplode.spr"
					ignoredClass = "0"
					iMagnitude = "100"
					iRadiusOverride = "0"
					parentname = "root"
					rendermode = "5"
					spawnflags = "1"
					targetname = "explode"
					origin = Vector( 0, 16, 42 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // VmutVendor

RegisterEntityGroup( "VmutVendor", ::VMutVendorEnt )
